package nh.logTrace.save.db.sql.jdbc;

public class OracleSql extends Sql {

    // TODO 오라클의 경우 if exist 사용이 불가능하므로 다른방법+기존 소스 수정없이 테이블 추가하는법 찾아야함
    private String ORACLE_CREATE_TABLE = "CREATE TABLE logtrace (\n" +
            "    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,\n" +
            "    transaction_id VARCHAR2(255),\n" +
            "    class_name VARCHAR2(255),\n" +
            "    method_name VARCHAR2(255),\n" +
            "    args CLOB,\n" +
            "    result CLOB,\n" +
            "    throwable_message VARCHAR2(255),\n" +
            "    throwable_stack_trace VARCHAR2(255),\n" +
            "    created_at TIMESTAMP\n" +
            ");";

    private String ORACLE_INSERT = "INSERT INTO logtrace (\n" +
            "    transaction_id, class_name, method_name, args, result, throwable_message, throwable_stack_trace, created_at\n" +
            ") VALUES (\n" +
            "    ?, ?, ?, ?, ?, ?, ?, ?\n" +
            ");";

    private String ORACLE_SELECT = "SELECT * FROM logtrace WHERE id = ?;";
    private String ORACLE_SELECT_ALL = "SELECT * FROM logtrace";

    public OracleSql() {
        this.createTableSql = ORACLE_CREATE_TABLE;
        this.insertSql = ORACLE_INSERT;
        this.selectSql = ORACLE_SELECT;
        this.selectAllSql = ORACLE_SELECT_ALL;
    }
}
